export default [
  {
    "id": "QZ001",
    "title": "Quiz 1",
    "published":true,
    "description": "This is an example of a graded quiz.",
    "course": "RS101",
    "assignTo": "Everyone",
    "type": "Graded Quiz",
    "points": 100,
    "group": "Quizzes",
    "shuffleAnswers": true,
    "timeLimit": true,
    "quiz_limit_time": 20,
    "multipleAttempts": false,
    "attempt_limit": 1,
    "showCorrectAnswers": true,
    "displayGradeAs": "Number",
    "correct_answers_visibility": 1,
    "accessCode": false,
    "oneQuestionAtTime": true,
    "webcamReq": false,
    "lockQuestions": false,
    "dueDate": "2024-05-15",
    "availableDate": "2024-01-10",
    "availableUntil": "2024-01-10",
  },
];

