export default [
  {
    "quiz_id": "QZ001",
    "quiz_name": "Quiz 1",
    "publish_status":true,
    "description": "This is an example of a graded quiz.",
    "course_id": "RS101",
    "quiz_type": "Graded Quiz",
    "points": 100,
    "assignment_group": "Quizzes",
    "shuffle_answers": true,
    "time_limit": true,
    "quiz_limit_time": 20,
    "multiple_attempts": false,
    "attempt_limit": 1,
    "show_correct_answers": true,
    "correct_answers_visibility": 1,//immad
    "access_code": false,
    "one_question_at_a_time": true,
    "webcam_required": false,
    "lock_questions_after_answering": false,
    "due_date": "2024-05-15",
    "available_date": "2024-01-10",
    "until_date": "2024-01-10",
  },
  {
    "quiz_id": "QZ002",
    "quiz_name": "Quiz 2",
    "publish_status":false,
    "description": "This is an example of a graded quiz.",
    "course_id": "RS101",
    "quiz_type": "Graded Quiz",
    "points": 100,
    "assignment_group": "Quizzes",
    "shuffle_answers": true,
    "time_limit": true,
    "quiz_limit_time": 20,
    "multiple_attempts": false,
    "attempt_limit": 1,
    "show_correct_answers": true,
    "correct_answers_visibility": 1,
    "access_code": false,
    "one_question_at_a_time": true,
    "webcam_required": false,
    "lock_questions_after_answering": false,
    "due_date": "2024-05-15",
    "available_date": "2024-01-10",
    "until_date": "2024-01-10",
  }
];

